sudo: false        #Use new Container Infrastructure
language: python
python:
  - 3.6

notifications:
  email: false

branches:
  only:
    - master

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda env create -f environment.yml

script:
  - source activate pecanpy-dev
  - python setup.py install
